from __future__ import annotations

ENGINE_REGISTRY = {
    "pyfao56": {
        "role": "irrigation_water_balance",
        "rollout": "shadow",
        "upstream": "kthorp/pyfao56",
        "upstream_commit": "1d242ee985be0edbc4946f06e7e94a487d4bc0c9",
        "package": "pyfao56==1.4.3",
        "license": "CC0-1.0 / public domain dedication",
        "adapter_version": 1,
        "production_authority": False,
    },
    "pcse": {
        "role": "crop_phenology_growth",
        "rollout": "pilot",
        "upstream": "ajwdewit/pcse",
        "upstream_commit": "0d51ae84f405fd9b061222f2a0130e5351f460df",
        "package": "pcse==6.0.13",
        "license": "EUPL-1.1-or-later (upstream LICENSE)",
        "adapter_version": 2,
        "production_authority": False,
        "pilot_model": "Wofost72_PP",
        "water_stress_authority": False,
    },
    "aquacrop": {
        "role": "seasonal_irrigation_yield_scenarios",
        "rollout": "pilot",
        "upstream": "aquacropos/aquacrop",
        "upstream_commit": "36cc20e44644ed1704398889312435c85e04a2f3",
        "package": "aquacrop==3.1.0",
        "license": "Apache-2.0 (upstream LICENSE)",
        "adapter_version": 2,
        "production_authority": False,
    },
    "autogeobound": {
        "role": "automatic_field_boundary_research",
        "rollout": "off",
        "upstream": "agstack/autogeobound",
        "upstream_commit": "7087b59e51438ec370b698186805751be9296ec2",
        "license": "Apache-2.0",
        "adapter_version": 0,
        "production_authority": False,
    },
    "openagri-pest-disease": {
        "role": "pest_disease_risk_benchmark",
        "rollout": "off",
        "upstream": "agstack/OpenAgri-PestAndDiseaseManagement",
        "upstream_commit": "3aa67a9ad3de6ff8a772dc635db041ec53845aa4",
        "license": "EUPL-1.2",
        "adapter_version": 0,
        "production_authority": False,
    },
    "agml": {
        "role": "disease_vision_research",
        "rollout": "off",
        "upstream": "Project-AgML/AgML",
        "upstream_commit": "c3343fc3b3f8abd89983927da3fc8319cb019d49",
        "license": "Apache-2.0",
        "adapter_version": 0,
        "production_authority": False,
    },
    "farmvibes-ai": {
        "role": "geospatial_pipeline_reference",
        "rollout": "off",
        "upstream": "microsoft/farmvibes-ai",
        "upstream_commit": "d10670e18742d05aec50f73e4695d47978908994",
        "license": "MIT",
        "adapter_version": 0,
        "production_authority": False,
    },
}
