import { useEffect, useRef, useState } from 'react';
import type { SatelliteHealthResult } from '../../../lib/satelliteService';
import { clearSatelliteHistoryPreviewCache, fetchHistoricalSatellite, fetchHistoricalSatellitePreview, listSatelliteDates } from '../services/satelliteHistory';
const PREVIEW_LIMIT=6;
export function useSatelliteHistory(fieldId:string|undefined,geometry:unknown){
 const[open,setOpen]=useState(false),[dates,setDates]=useState<string[]>([]),[previews,setPreviews]=useState<Record<string,string>>({}),[loading,setLoading]=useState(false),[previewLoading,setPreviewLoading]=useState(false),[error,setError]=useState<string|null>(null),[selection,setSelection]=useState<{fieldId:string;data:SatelliteHealthResult}|null>(null);
 const request=useRef(0),cache=useRef(new Map<string,SatelliteHealthResult>()),previewInflight=useRef(new Map<string,Promise<string>>());
 useEffect(()=>{request.current++;setOpen(false);setSelection(null);setDates([]);setPreviews({});setError(null);setLoading(false);setPreviewLoading(false);cache.current.clear();previewInflight.current.clear();clearSatelliteHistoryPreviewCache();return()=>{request.current++}},[fieldId]);
 async function ensurePreview(date:string){if(!geometry||!date)return null;if(previews[date])return previews[date];const full=cache.current.get(date);if(full?.ndviImage){setPreviews(c=>({...c,[date]:full.ndviImage!}));return full.ndviImage}let pending=previewInflight.current.get(date);if(!pending){pending=fetchHistoricalSatellitePreview(geometry,date);previewInflight.current.set(date,pending);void pending.finally(()=>previewInflight.current.delete(date))}try{const image=await pending;setPreviews(c=>({...c,[date]:image}));return image}catch{return null}}
 useEffect(()=>{const handler=(event:Event)=>{const date=String((event as CustomEvent)?.detail?.date??'');if(date&&dates.includes(date))void ensurePreview(date)};window.addEventListener('tp:satellite-history-preview-request',handler);return()=>window.removeEventListener('tp:satellite-history-preview-request',handler)},[dates,geometry,previews]);
 async function warmPreviews(items:string[],id:number){if(!geometry||!items.length)return;setPreviewLoading(true);try{for(const date of items.slice(0,PREVIEW_LIMIT)){if(id!==request.current)return;await ensurePreview(date)}}finally{if(id===request.current)setPreviewLoading(false)}}
 async function show(){setOpen(true);setError(null);if(!fieldId||!geometry){setError('Önce parsel sınırları olan bir tarla ekle.');return}if(dates.length){void warmPreviews(dates.filter(d=>!previews[d]),request.current);return}const id=++request.current;setLoading(true);try{const result=await listSatelliteDates(geometry);if(id!==request.current)return;setDates(result);setLoading(false);void warmPreviews(result,id)}catch(caught){if(id===request.current)setError(caught instanceof Error?caught.message:'Tarihler alınamadı.')}finally{if(id===request.current)setLoading(false)}}
 async function select(date:string|null){if(!date){request.current++;setSelection(null);setLoading(false);setPreviewLoading(false);setOpen(false);return}if(!fieldId||!geometry)return;const id=++request.current;setError(null);setLoading(true);try{const result=cache.current.get(date)??await fetchHistoricalSatellite(geometry,date);if(id!==request.current)return;cache.current.set(date,result);if(result.ndviImage)setPreviews(c=>({...c,[date]:result.ndviImage!}));setSelection({fieldId,data:result});setOpen(false)}catch(caught){if(id===request.current)setError(caught instanceof Error?caught.message:'Görüntü alınamadı.')}finally{if(id===request.current)setLoading(false)}}
 function close(){request.current++;setOpen(false);setLoading(false);setPreviewLoading(false)}
 return{open,dates,previews,loading,previewLoading,error,show,select,close,ensurePreview,data:selection?.fieldId===fieldId?selection?.data??null:null};
}
